### ISSUE TITLE
codedeployAwsProfile does not work

### ISSUE THREAD

**Issue by MojoJojo** [myyk/sbt-codedeploy#3]
When I try to specify a profile for AWS client, I get the following error:

```
build.sbt:13: error: not found: value codedeployAwsProfile
codedeployAwsProfile := "mydevprofile"
```

Have also tried:

```
.settings(codedeployAwsProfile := "mydevprofile")
```

The variable does not even existing in CodeDeploy.scala. Looking at the code, it seems like AWSCredentialsProvider is the way to go?

**Comment by MojoJojo** [comment]
This works:

In build.sbt:

```
libraryDependencies += "com.amazonaws" % "aws-java-sdk-core" % "1.11.26"  force()
import com.amazonaws.auth.profile.ProfileCredentialsProvider
lazy val server =
  DefProject("designer/server", "server")
.settings(codedeployAWSCredentialsProvider := Option(new ProfileCredentialsProvider("mydevprofile")))
```

**Comment by myyk** [comment]
Sorry, looks like I need to update the docs, `codedeployAWSCredentialsProvider` is the right name for that variable now.

I just pushed a commit updating that. Does that look right to you? https://github.com/myyk/sbt-codedeploy/commit/5b334116779a31199cf43e0c1e949dba27608c0e

Thanks!

**Comment by myyk** [comment]
Thanks, I think this is fixed now that the docs are fixed.
